swagger: '2.0'
info:
  version: '1.0'
  title: WLUSM
  description: API для сервиса по скачиванию альбомов из ВК.
schemes:
  - http
  - https
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
consumes:
  - application/json
host: localhost:5000
basePath: /v1.0
paths:
  '/authorization/code':
    post:
      tags:
        - account
      summary: Запрос на регистрацию пользователя
      produces:
        - application/json
      operationId: register_user
      parameters:
        - name: json
          in: body
          description: Данные пользователя для регистрации
          required: true
          schema:
            type: object
            required:
              - code
            properties:
              code:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
  '/community':
    get:
      tags:
        - community
      summary: Запрос на получение всех сообществ
      operationId: community_get
      security:
        - ApiKeyAuth: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
  '/tasks':
    get:
      tags:
        - tasks
      summary: Запрос на получение всех задач
      operationId: tasks_get
      security:
        - ApiKeyAuth: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
  '/notifications':
    get:
      tags:
        - notifications
      summary: Запрос на получение всех notifications
      operationId: notifications_get
      security:
        - ApiKeyAuth: []
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/start'
        - $ref: '#/parameters/limit'
        - name: start_time
          in: query
          default: null
          type: number
        - name: end_time
          in: query
          default: null
          type: number
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
  '/notification/{notificationId}':
    put:
      tags:
        - notifications
      summary: Запрос на изменение уведомления
      security:
        - ApiKeyAuth: []
      produces:
        - application/json
      operationId: notification_update
      parameters:
        - name: notificationId
          in: path
          required: true
          type: string
        - name: json
          in: body
          required: true
          schema:
            type: object
            properties:
              hide:
                type: boolean
                default: false
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
    delete:
      tags:
        - notifications
      summary: Запрос на регистрацию приложения
      produces:
        - application/json
      operationId: notification_delete
      security:
        - ApiKeyAuth: []
      parameters:
        - name: notificationId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
  '/users':
    get:
      tags:
        - users
      summary: Запрос на получение пользователя
      operationId: users_get
      security:
        - ApiKeyAuth: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/response'
definitions:
  response:
    type: object
    properties:
      status:
        type: string
      code:
        type: number
      result:
        type: object
parameters:
  lang:
    name: lang
    in: query
    type: string
    description: >
      Language:
       * `en` - english
       * `ru` - russian
  start:
    name: start
    in: query
    type: integer
    default: 0
  limit:
    name: limit
    in: query
    type: integer
    default: 50